### testing signing commit from mac 10-03-22 11:25 AM
- hosts: all
  tasks:
  - name: ansible create directory example
    file:
      path: /tmp/devops_directory
      state: directory         # specify state=directory default is file
